### ISSUE TITLE
How does the DCA spreadsheet file work?

### ISSUE THREAD

**Issue by huytrvan** [hippocritical/strategies#1]
Hi Hippo,

Thanks for sharing the .ods file with us. I am having difficulties interpreting some of the columns and how they work together.

It would be helpful if you could provide a README file that explains the logic and mechanics of your DCA in more details. This way, we could try to optimize it for our own use-case.

Thanks!

**Comment by hippocritical** [comment]
Hi, 

The file works along the ways that you have general variables in the top that you configured, as A2 is the maximum safety order depth for example.

The rows 19-28 is the calculation of the slots etc where row 25 is the result how much % you should use of a stake and the row 28 is the result in $ assuming you have 500/2 overall stake (from F2)

The rows 30-36 are just the outputs for the overbuy factors if you wanted to use 4+0 to 4+4

The columns from B to M are scaling up the max_so_multiplier.

If you want to edit the excel sheet it breaks easily, it was just an afterthought so people can look at it rather than editing it.
If you want to edit it you could easier take the formulas from the cells and build your own spreadsheet imo.
That includes the max_so_multiplier variable.

If you just want to scale more or less hard then you could just take the values from B10 to M10 . Harder scaling means that you start less deep and progress harder into the overall slot size (times overbuy)

Hope that helped

**Comment by huytrvan** [comment]
Thanks Hippo, let me look into it.
